%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters - Freiburg 1
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Freiburg1 Kinect Calibration
Camera.fx: 517.3
Camera.fy: 516.5
Camera.cx: 318.6
Camera.cy: 255.3

# Distortion parameters
Camera.k1: 0.2624
Camera.k2: -0.9531
Camera.p1: -0.0054
Camera.p2: 0.0026
Camera.k3: 1.1633

Camera.width: 640
Camera.height: 480
Camera.fps: 30.0
Camera.RGB: 1

# Depth parameters
DepthMapFactor: 5000.0
ThDepth: 40.0

# Baseline times fx (required even for RGB-D)
Camera.bf: 40.0

#--------------------------------------------------------------------------------------------
# IMU Parameters
#--------------------------------------------------------------------------------------------
IMU.NoiseGyro: 0.01
IMU.NoiseAcc: 0.1
IMU.GyroWalk: 0.0001
IMU.AccWalk: 0.001
IMU.Frequency: 200

# Transformation from camera to IMU
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

InsertKFsWhenLost: 0

#--------------------------------------------------------------------------------------------
# ORB Extractor Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
